RGBLIGHT_ENABLE   = no
BACKLIGHT_ENABLE  = no
AUDIO_ENABLE      = no
COMMAND_ENABLE    = no
CONSOLE_ENABLE    = no
UNICODE_ENABLE    = no
SWAP_HANDS_ENABLE = no
MOUSEKEY_ENABLE   = no
BOOTMAGIC_ENABLE  = no

EXTRAKEY_ENABLE   = yes

EXTRAFLAGS        += -flto